# ML to predict Bitcoin prices

+ Data from: https://coinmarketcap.com/api/
+ Adapted from: https://dashee87.github.io/data%20science/deep%20learning/python/another-keras-tutorial-for-neural-network-beginners/
+ Adapted from: https://dashee87.github.io/deep%20learning/python/predicting-cryptocurrency-prices-with-deep-learning/
+ Adapted from: https://github.com/dashee87/blogScripts/blob/master/Jupyter/2017-11-20-predicting-cryptocurrency-prices-with-deep-learning.ipynb

In [1]:
import pandas as pd
import time
import seaborn as sns
import matplotlib.pyplot as plt
import datetime
import numpy as np

# get market info for bitcoin from the start of 2016 to the current day
bitcoin_market_info = pd.read_html("https://coinmarketcap.com/currencies/bitcoin/historical-data/?start=20130428&end="+time.strftime("%Y%m%d"))[0]

# convert the date string to the correct date format
bitcoin_market_info = bitcoin_market_info.assign(Date=pd.to_datetime(bitcoin_market_info['Date']))
# when Volume is equal to '-' convert it to 0
bitcoin_market_info.loc[bitcoin_market_info['Volume']=="-",'Volume']=0
# convert to int
bitcoin_market_info['Volume'] = bitcoin_market_info['Volume'].astype('int64')
# look at the first few rows
bitcoin_market_info.head()

Date     Open     High      Low    Close      Volume    Market Cap
0 2018-04-15  7999.33  8338.42  7999.33  8329.11  5244480000  135812000000
1 2018-04-14  7874.67  8140.71  7846.00  7986.24  5191430000  133682000000
2 2018-04-13  7901.09  8183.96  7758.93  7895.96  7764460000  134114000000
3 2018-04-12  6955.38  7899.23  6806.51  7889.25  8906250000  118048000000
4 2018-04-11  6843.47  6968.32  6817.59  6968.32  4641890000  116126000000

In [2]:
bitcoin_market_info.columns =[bitcoin_market_info.columns[0]]+['bt_'+i for i in bitcoin_market_info.columns[1:]]

In [3]:
# market_info = pd.merge(bitcoin_market_info,eth_market_info, on=['Date'])
# market_info = market_info[market_info['Date']>='2016-01-01']
market_info = bitcoin_market_info
market_info = market_info[market_info['Date']>='2016-01-01']
for coins in ['bt_']: 
    kwargs = { coins+'day_diff': lambda x: (x[coins+'Close']-x[coins+'Open'])/x[coins+'Open']}
    market_info = market_info.assign(**kwargs)
market_info.head()

Date  bt_Open  bt_High   bt_Low  bt_Close   bt_Volume  bt_Market Cap  \
0 2018-04-15  7999.33  8338.42  7999.33   8329.11  5244480000   135812000000   
1 2018-04-14  7874.67  8140.71  7846.00   7986.24  5191430000   133682000000   
2 2018-04-13  7901.09  8183.96  7758.93   7895.96  7764460000   134114000000   
3 2018-04-12  6955.38  7899.23  6806.51   7889.25  8906250000   118048000000   
4 2018-04-11  6843.47  6968.32  6817.59   6968.32  4641890000   116126000000   

   bt_day_diff  
0     0.041226  
1     0.014168  
2    -0.000649  
3     0.134266  
4     0.018244

In [4]:
for coins in ['bt_']: 
    kwargs = { coins+'close_off_high': lambda x: 2*(x[coins+'High']- x[coins+'Close'])/(x[coins+'High']-x[coins+'Low'])-1,
            coins+'volatility': lambda x: (x[coins+'High']- x[coins+'Low'])/(x[coins+'Open'])}
    market_info = market_info.assign(**kwargs)

In [5]:
model_data = market_info[['Date']+[coin+metric for coin in ['bt_'] 
                                   for metric in ['Close','Volume','close_off_high','volatility']]]
# need to reverse the data frame so that subsequent rows represent later timepoints
model_data = model_data.sort_values(by='Date')
model_data.head()

Date  bt_Close  bt_Volume  bt_close_off_high  bt_volatility
835 2016-01-01    434.33   36278900          -0.560641       0.020292
834 2016-01-02    433.44   30096600           0.250597       0.009641
833 2016-01-03    430.01   39633800          -0.173865       0.020827
832 2016-01-04    433.09   38477500          -0.474265       0.012649
831 2016-01-05    431.96   34522600          -0.013333       0.010391

In [6]:
split_date = '2017-06-01'
# we don't need the date columns anymore
training_set, test_set = model_data[model_data['Date']<split_date], model_data[model_data['Date']>=split_date]
training_set = training_set.drop('Date', 1)
test_set = test_set.drop('Date', 1)

bt_Close   bt_Volume  bt_close_off_high  bt_volatility
318   2407.88  1653180000          -0.493815       0.069946
317   2488.55  1317030000          -1.000000       0.047932
316   2515.35  1514950000          -0.159278       0.063496
315   2511.81  1355120000           0.111061       0.052339
314   2686.81  1369310000          -1.000000       0.070287
313   2863.20  2089610000          -0.115346       0.114860
312   2732.16  1517710000           0.625637       0.058835
311   2805.62  1281170000          -0.865882       0.053060
310   2823.81  1348950000           0.468564       0.037789
309   2947.71  2018890000          -0.967912       0.072288
308   2958.11  1752400000          -0.506760       0.053042
307   2659.63  2569530000           0.410612       0.162094
306   2717.02  1781200000           0.038800       0.051721
305   2506.37  1696560000           0.500227       0.137617
304   2464.58  2026260000          -0.564071       0.128722
303   2518.56  1195190000          -0.723978       0.062671
302   2655.88  1534510000          -0.707237       0.079646
301   2548.29  1178660000           0.561501       0.054897
300   2589.60  1446840000           0.287120       0.044652
299   2721.79  1854190000          -0.520129       0.067006
298   2689.10  1626580000           0.485709       0.041193
297   2705.41  1097940000          -0.549521       0.030241
296   2744.91   961319000          -0.310884       0.021719
295   2608.72   982750000           0.707811       0.063812
294   2589.41  1161100000           0.426925       0.049915
293   2478.45  1663280000           0.144961       0.092242
292   2552.45  1489790000          -1.000000       0.088547
291   2574.79  1183870000          -0.511710       0.046831
290   2539.32   949979000           0.263816       0.030515
289   2480.84   860273000           0.940361       0.031828
..        ...         ...                ...            ...
29    7916.88  4426150000           0.610050       0.064133
28    8223.68  6639190000          -0.948485       0.107410
27    8630.65  6729110000          -0.816726       0.059140
26    8913.47  6361790000          -0.583894       0.076700
25    8929.28  6043130000           0.498852       0.037040
24    8728.47  5530390000           0.389448       0.059938
23    8879.62  5954120000          -1.000000       0.059408
22    8668.12  5664600000           0.985355       0.037124
21    8495.78  4569880000           0.599158       0.027042
20    8209.40  5921040000           0.053742       0.071619
19    7833.04  5378250000           0.835775       0.053110
18    7954.48  4935290000           0.073633       0.040031
17    7165.70  6361230000           0.815280       0.114418
16    6890.52  6289510000           0.302920       0.082651
15    6973.53  4553270000           0.361020       0.049957
14    6844.23  4532100000          -0.188436       0.076264
13    7083.80  4333440000          -0.675938       0.046588
12    7456.11  5499700000          -0.673552       0.064550
11    6853.84  4936000000           0.849970       0.089319
10    6811.47  5639320000          -0.153346       0.042201
9     6636.32  3766810000           0.565861       0.041445
8     6911.09  3976610000          -0.336000       0.063348
7     7023.52  3652500000          -0.080906       0.027685
6     6770.73  4894060000           0.578625       0.073268
5     6834.76  4272750000          -0.552478       0.024761
4     6968.32  4641890000          -1.000000       0.022025
3     7889.25  8906250000          -0.981734       0.157104
2     7895.96  7764460000           0.355198       0.053794
1     7986.24  5191430000           0.048285       0.037425
0     8329.11  5244480000          -0.945088       0.042390

[319 rows x 4 columns]

In [7]:
window_len = 1
norm_cols = [coin+metric for coin in ['bt_'] for metric in ['Close','Volume']]

In [8]:
LSTM_training_inputs = []
for i in range(len(training_set)-window_len):
    temp_set = training_set[i:(i+window_len)].copy()
    for col in norm_cols:
        temp_set.loc[:, col] = temp_set[col]/temp_set[col].iloc[0] - 1
    LSTM_training_inputs.append(temp_set)
LSTM_training_outputs = (training_set['bt_Close'][window_len:].values/training_set['bt_Close'][:-window_len].values)-1

In [9]:
LSTM_test_inputs = []
for i in range(len(test_set)-window_len):
    temp_set = test_set[i:(i+window_len)].copy()
    for col in norm_cols:
        temp_set.loc[:, col] = temp_set[col]/temp_set[col].iloc[0] - 1
    LSTM_test_inputs.append(temp_set)
LSTM_test_outputs = (test_set['bt_Close'][window_len:].values/test_set['bt_Close'][:-window_len].values)-1

In [10]:
LSTM_training_inputs = [np.array(LSTM_training_input) for LSTM_training_input in LSTM_training_inputs]
LSTM_training_inputs = np.array(LSTM_training_inputs)

LSTM_test_inputs = [np.array(LSTM_test_inputs) for LSTM_test_inputs in LSTM_test_inputs]
LSTM_test_inputs = np.array(LSTM_test_inputs)

In [11]:
# import the relevant Keras modules
from keras.models import Sequential
from keras.layers import Activation, Dense
from keras.layers import LSTM
from keras.layers import Dropout

def build_model(inputs, output_size, neurons, activ_func="linear",
                dropout=0.25, loss="mae", optimizer="adam"):
    model = Sequential()

    model.add(LSTM(neurons, input_shape=(inputs.shape[1], inputs.shape[2])))
    model.add(Dropout(dropout))
    model.add(Dense(units=output_size))
    model.add(Activation(activ_func))

    model.compile(loss=loss, optimizer=optimizer)
    return model

Using TensorFlow backend.


In [12]:
# random seed for reproducibility
np.random.seed(202)
# we'll try to predict the closing price for the next 5 days 
# change this value if you want to make longer/shorter prediction
pred_range = 1
# initialise model architecture
bt_model = build_model(LSTM_training_inputs, output_size=pred_range, neurons = 20)
# model output is next 5 prices normalised to 10th previous closing price
LSTM_training_outputs = []
for i in range(window_len, len(training_set['bt_Close'])-pred_range):
    LSTM_training_outputs.append((training_set['bt_Close'][i:i+pred_range].values/
                                  training_set['bt_Close'].values[i-window_len])-1)
LSTM_training_outputs = np.array(LSTM_training_outputs)
# train model on data
# note:bt_history contains information on the training error per epoch
bt_history = bt_model.fit(LSTM_training_inputs[:-pred_range], LSTM_training_outputs, 
                            epochs=50, batch_size=1, verbose=2, shuffle=True)

Epoch 1/50
 - 2s - loss: 0.0237
Epoch 2/50
 - 1s - loss: 0.0221
Epoch 3/50
 - 1s - loss: 0.0212
Epoch 4/50
 - 1s - loss: 0.0206
Epoch 5/50
 - 1s - loss: 0.0197
Epoch 6/50
 - 1s - loss: 0.0193
Epoch 7/50
 - 1s - loss: 0.0189
Epoch 8/50
 - 1s - loss: 0.0190
Epoch 9/50
 - 1s - loss: 0.0191
Epoch 10/50
 - 1s - loss: 0.0190
Epoch 11/50
 - 1s - loss: 0.0189
Epoch 12/50
 - 1s - loss: 0.0187
Epoch 13/50
 - 1s - loss: 0.0188
Epoch 14/50
 - 1s - loss: 0.0188
Epoch 15/50
 - 1s - loss: 0.0187
Epoch 16/50
 - 1s - loss: 0.0186
Epoch 17/50
 - 1s - loss: 0.0187
Epoch 18/50
 - 1s - loss: 0.0188
Epoch 19/50
 - 1s - loss: 0.0186
Epoch 20/50
 - 1s - loss: 0.0185
Epoch 21/50
 - 1s - loss: 0.0187
Epoch 22/50
 - 1s - loss: 0.0186
Epoch 23/50
 - 1s - loss: 0.0186
Epoch 24/50
 - 1s - loss: 0.0186
Epoch 25/50
 - 1s - loss: 0.0187
Epoch 26/50
 - 1s - loss: 0.0186
Epoch 27/50
 - 1s - loss: 0.0186
Epoch 28/50
 - 1s - loss: 0.0185
Epoch 29/50
 - 1s - loss: 0.0186
Epoch 30/50
 - 1s - loss: 0.0186
Epoch 31/50
 - 1s -

In [13]:
bt_pred_prices = ((bt_model.predict(LSTM_test_inputs)[:-pred_range][::pred_range]+1)*\
                   test_set['bt_Close'].values[:-(window_len + pred_range)][::pred_range].reshape(int(np.ceil((len(LSTM_test_inputs)-pred_range)/float(pred_range))),1))

In [14]:
bt_pred_prices = ((bt_model.predict(LSTM_test_inputs)[:-pred_range][::pred_range]+1)*\
                   test_set['bt_Close'].values[:-(window_len + pred_range)][::pred_range].reshape(int(np.ceil((len(LSTM_test_inputs)-pred_range)/float(pred_range))),1))

In [15]:
bt_pred_prices

array([[  2420.51528701],
       [  2498.23500279],
       [  2529.79242391],
       [  2526.44978464],
       [  2698.59324855],
       [  2887.28388319],
       [  2753.79291779],
       [  2817.23264563],
       [  2840.17162818],
       [  2960.9034547 ],
       [  2971.74283784],
       [  2698.13001461],
       [  2732.2767041 ],
       [  2539.8515767 ],
       [  2482.17573176],
       [  2530.11697466],
       [  2669.49498924],
       [  2567.06663194],
       [  2604.6255681 ],
       [  2735.63644368],
       [  2705.47834277],
       [  2715.56293744],
       [  2754.8237471 ],
       [  2631.32260324],
       [  2606.37916055],
       [  2499.02100311],
       [  2564.67945099],
       [  2586.06171673],
       [  2551.59460941],
       [  2497.38778974],
       [  2450.25356678],
       [  2516.57762062],
       [  2575.37399642],
       [  2612.14660113],
       [  2612.03336288],
       [  2616.84689521],
       [  2565.54937825],
       [  2580.41137823],
       [  25

In [16]:
test_price = (bt_model.predict(LSTM_test_inputs))

Querying like above, without the full calculation, returns wrong results. Calculation:

```
bt_pred_prices = ((bt_model.predict(LSTM_test_inputs)[:-pred_range][::pred_range]+1)*\
                   test_set['bt_Close'].values[:-(window_len + pred_range)[::pred_range].reshape(int(np.ceil((len(LSTM_test_inputs)-pred_range)/float(pred_range))),1))
```
Think the solution into read in and prepare data (test_set, LSTM_test_inputs) from scratch using only one days worth of data.

In [17]:
test_price

array([[ 0.00524752],
       [ 0.00389181],
       [ 0.0057417 ],
       [ 0.00582843],
       [ 0.00438556],
       [ 0.00841149],
       [ 0.00791784],
       [ 0.00413901],
       [ 0.00579415],
       [ 0.00447588],
       [ 0.00460863],
       [ 0.01447575],
       [ 0.00561528],
       [ 0.01335863],
       [ 0.00713947],
       [ 0.00458873],
       [ 0.00512634],
       [ 0.00736837],
       [ 0.00580224],
       [ 0.00508721],
       [ 0.00609065],
       [ 0.00375282],
       [ 0.00361164],
       [ 0.00866427],
       [ 0.00655334],
       [ 0.00829995],
       [ 0.00479123],
       [ 0.00437776],
       [ 0.00483386],
       [ 0.00667023],
       [ 0.00645034],
       [ 0.00403266],
       [ 0.00441251],
       [ 0.00403845],
       [ 0.00385992],
       [ 0.00317683],
       [ 0.01861675],
       [ 0.00352791],
       [ 0.00819049],
       [ 0.00956339],
       [ 0.00610805],
       [ 0.00471327],
       [ 0.00592845],
       [ 0.00850762],
       [ 0.0138896 ],
       [ 0

In [18]:
# get market info for bitcoin from the start of 2016 to the current day
bitcoin_market_new = pd.read_html("https://coinmarketcap.com/currencies/bitcoin/historical-data/?start=20180415&end=20180416")[0]

# convert the date string to the correct date format
bitcoin_market_new = bitcoin_market_new.assign(Date=pd.to_datetime(bitcoin_market_info['Date']))

# convert to int
bitcoin_market_new['Volume'] = bitcoin_market_new['Volume'].astype('int64')

# look at the first few rows
bitcoin_market_new.head()

bitcoin_market_new.columns =[bitcoin_market_new.columns[0]]+['bt_'+i for i in bitcoin_market_new.columns[1:]]

market_new = bitcoin_market_new
market_new = market_new[market_new['Date']>='2016-01-01']

for coins in ['bt_']: 
    kwargs = { coins+'day_diff': lambda x: (x[coins+'Close']-x[coins+'Open'])/x[coins+'Open']}
    market_new = market_new.assign(**kwargs)
market_new.head()

for coins in ['bt_']: 
    kwargs = { coins+'close_off_high': lambda x: 2*(x[coins+'High']- x[coins+'Close'])/(x[coins+'High']-x[coins+'Low'])-1,
            coins+'volatility': lambda x: (x[coins+'High']- x[coins+'Low'])/(x[coins+'Open'])}
    market_new = market_new.assign(**kwargs)
    
m_data = market_new[['Date']+[coin+metric for coin in ['bt_'] 
                                   for metric in ['Close','Volume','close_off_high','volatility']]]

# need to reverse the data frame so that subsequent rows represent later timepoints
m_data = m_data.sort_values(by='Date')
m_data.head()

predict_set = m_data.drop('Date', 1)

window_len = 1
norm_cols = [coin+metric for coin in ['bt_'] for metric in ['Close','Volume']]

LSTM_predict_inputs = []

for i in range(len(predict_set)):#-window_len):
    temp_set = predict_set[i:(i+window_len)].copy()
    for col in norm_cols:
        temp_set.loc[:, col] = temp_set[col]/temp_set[col].iloc[0] - 1
    LSTM_predict_inputs.append(temp_set)
LSTM_test_outputs = (test_set['bt_Close'][window_len:].values/test_set['bt_Close'][:-window_len].values)-1

LSTM_predict_inputs = [np.array(LSTM_predict_inputs) for LSTM_predict_inputs in LSTM_predict_inputs]
LSTM_predict_inputs = np.array(LSTM_predict_inputs)

LSTM_predict_inputs

array([[[ 0.        ,  0.        , -0.94508832,  0.0423898 ]]])

In [19]:
((bt_model.predict(LSTM_predict_inputs)+1)*\
                   predict_set['bt_Close'].values.reshape(1,1))

array([[ 8360.82147289]])